const LOGIN_ERRORS = {
  FORMAT_REMINDER: 'FORMAT_REMINDER',
  MISSING_REMINDER: 'MISSING_REMINDER',
  NO_ACCOUNT: 'NO_ACCOUNT',
  WRONG: 'WRONG',
  WRONG_EMAIL_FORMAT: 'WRONG_EMAIL_FORMAT'
};

export { LOGIN_ERRORS };
